apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyancms-api
  annotations:
    kubernetes.io/change-cause: "Initial deployment of the API"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyancms-api
  template:
    metadata:
      name: cyancms-apik8s
      labels:
        env: prod
        app: cyancms-api
        app.kubernetes.io/name: cyancms-api
    spec:
      containers:
        - name: cyancms-api
          image: sergionarvasta/cyancms.api
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URL
              value: "http://+:80"
apiVersion: v1
kind: Service
metadata: 
  name: load-balancer  
spec: 
  selector:   
    app.kubernetes.io/name: cyancms-api
  ports: 
    - name: cyancms-port
      protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - "20.246.147.109"